services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: subvision-server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    restart: always
    depends_on:
      - rabbitmq
      - minio

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: subvision-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    restart: always
    depends_on:
      - server

  minio:
    image: minio/minio
    container_name: subvision-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: subvision-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minio minio123;
      mc mb -p local/subvision || true;
      mc anonymous set download local/subvision;
      exit 0;
      "

volumes:
  minio-data:
